In [1]:
!pip install -qU plotly torch colorlover
!rm -fr start; git clone --single-branch -b demos2018 -q https://github.com/harvard-ml-courses/cs281-demos start; cp -f start/cs281.py cs281.py
    

In [28]:
import torch 
import numpy as np
from plotly.offline import iplot 
import plotly.graph_objs as go
import cs281
import colorlover as cl
bupu = cl.scales['9']['seq']['BuPu']

In [7]:
x = torch.tensor([1.5,2])
x, x.shape

(tensor([1.5000, 2.0000]), torch.Size([2]))

In [11]:
W = torch.tensor([[0,2],[0.5,5]])
print(W)
print(W.shape)
W.numpy()

tensor([[0.0000, 2.0000],
        [0.5000, 5.0000]])
torch.Size([2, 2])


array([[0. , 2. ],
       [0.5, 5. ]], dtype=float32)

In [17]:
print(x+1)
print(x.add(1))
print("x is still {}.".format(x))


tensor([2.5000, 3.0000])
tensor([2.5000, 3.0000])
x is still tensor([1.5000, 2.0000])


In [18]:
# In-place ops (can be useful but be careful) 
x.add_(1)
print("x is now {}.".format(x))


x is now tensor([2.5000, 3.0000]).


In [19]:
print(x.shape)

torch.Size([2])


In [21]:
print(x.view(2,1).shape)

torch.Size([2, 1])


In [22]:
# Matrix multiplication
W@x

tensor([ 6.0000, 16.2500])

In [23]:
W@x.unsqueeze(1)

tensor([[ 6.0000],
        [16.2500]])

In [31]:
numpy_tensor = W.numpy()
torch_tensor = torch.tensor(np.array([[0,2.],[0.5,5]]))

In [32]:
numpy_tensor

array([[0. , 2. ],
       [0.5, 5. ]], dtype=float32)

In [33]:
torch_tensor

tensor([[0.0000, 2.0000],
        [0.5000, 5.0000]], dtype=torch.float64)

In [34]:
# Broadcasting. (be careful about this, but very useful)
print(W, x)
W + x 

tensor([[0.0000, 2.0000],
        [0.5000, 5.0000]]) tensor([2.5000, 3.0000])


tensor([[2.5000, 5.0000],
        [3.0000, 8.0000]])

In [37]:
W+x.unsqueeze(1)

tensor([[2.5000, 4.5000],
        [3.5000, 8.0000]])

### The main reason we will use PyTorch is because it automatically computes derivatives. Here we consider a simple function $$f(x) = x^2 + 10$$ 

In [45]:
def plot(x,y, color = None):
    "A simple plotting function, you can also use matplotlib."
    return [go.Scatter(dict(x = x.detach().numpy(),
                            y = y.detach().numpy(),
                            marker = dict(color=color)))]

In [48]:
# Create an arbitrary function over tensors. 
def fn(x):
    return x*x+10

x = torch.linspace(0,10,100)
y = fn(x)



In [50]:
iplot(plot(x,y))